//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.07 at 09:13:11 AM BRST 
//


package br.com.ecodif.eeml_contract;

import javax.xml.bind.annotation.XmlRegistry;



/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.ecodif.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.ecodif.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Eeml_Contract.Environment.Data.Unit }
     * 
     */
    public Eeml_Contract.Environment.Data.Unit createEemlEnvironmentDataUnit() {
        return new Eeml_Contract.Environment.Data.Unit();
    }

    /**
     * Create an instance of {@link Eeml_Contract.Environment.Data.Datapoints }
     * 
     */
    public Eeml_Contract.Environment.Data.Datapoints createEemlEnvironmentDataDatapoints() {
        return new Eeml_Contract.Environment.Data.Datapoints();
    }

    /**
     * Create an instance of {@link Eeml_Contract.Environment.Data }
     * 
     */
    public Eeml_Contract.Environment.Data createEemlEnvironmentData() {
        return new Eeml_Contract.Environment.Data();
    }

    /**
     * Create an instance of {@link Eeml_Contract.Environment.Data.Datapoints.Value }
     * 
     */
    public Eeml_Contract.Environment.Data.Datapoints.Value createEemlEnvironmentDataDatapointsValue() {
        return new Eeml_Contract.Environment.Data.Datapoints.Value();
    }

    /**
     * Create an instance of {@link Eeml_Contract.Environment.Data.CurrentValue }
     * 
     */
    public Eeml_Contract.Environment.Data.CurrentValue createEemlEnvironmentDataCurrentValue() {
        return new Eeml_Contract.Environment.Data.CurrentValue();
    }

    /**
     * Create an instance of {@link Eeml_Contract.Environment.Location }
     * 
     */
    public Eeml_Contract.Environment.Location createEemlEnvironmentLocation() {
        return new Eeml_Contract.Environment.Location();
    }

    /**
     * Create an instance of {@link Eeml_Contract.Environment }
     * 
     */
    public Eeml_Contract.Environment createEemlEnvironment() {
        return new Eeml_Contract.Environment();
    }

    /**
     * Create an instance of {@link Eeml_Contract }
     * 
     */
    public Eeml_Contract createEeml() {
        return new Eeml_Contract();
    }

}
