//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.07 at 09:13:11 AM BRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.eeml.org/xsd/0.5.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.ecodif.eeml_contract;
